### ISSUE TITLE
Runtime error while working with S7-400

### ISSUE THREAD

**Issue by JekRock** [robinson/gos7#3]
I'm getting a runtime error trying to read/write to S7-400 controller. The connection is ok, but when trying read/write (no matter what) I'm getting a runtime error.
Here are log messages
```
tcp: 2018/08/13 15:45:09 s7: sending 03 00 00 16 11 e0 00 00 00 01 00 c0 01 0a c1 02 01 00 c2 02 01 03
tcp: 2018/08/13 15:45:09 s7: received 03 00 00 16 11 d0 00 01 44 31 00 c0 01 0a c1 02 01 00 c2 02 01 03
tcp: 2018/08/13 15:45:09 s7: sending 03 00 00 19 02 f0 80 32 01 00 00 04 00 00 08 00 00 f0 00 00 01 00 01 01 e0
tcp: 2018/08/13 15:45:09 s7: received 03 00 00 1b 02 f0 80 32 03 00 00 04 00 00 08 00 00 00 00 f0 00 00 01 00 01 01 e0
tcp: 2018/08/13 15:45:10 s7: closing connection due to idle timeout: 100.0057ms

goroutine 6 [running]:
github.com/robinson/gos7.(*tcpTransporter).Send(0xc042076080, 0xc0420121e0, 0x27, 0x50, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/user/go/src/github.com/robinson/gos7/tcpclient.go:110 +0x100
github.com/robinson/gos7.(*client).send(0xc0420be240, 0xc04203be38, 0x4, 0x23, 0x27)
        C:/Users/user/go/src/github.com/robinson/gos7/client.go:463 +0x61
github.com/robinson/gos7.(*client).writeArea(0xc0420be240, 0x84, 0x1c7, 0x2, 0x4, 0x2, 0xc0420bc9bc, 0x4, 0x4, 0x0, ...)
        C:/Users/user/go/src/github.com/robinson/gos7/client.go:350 +0x61c
github.com/robinson/gos7.(*client).AGWriteDB(0xc0420be240, 0x1c7, 0x2, 0x4, 0xc0420bc9bc, 0x4, 0x4, 0x0, 0x0)
        C:/Users/user/go/src/github.com/robinson/gos7/client.go:81 +0x90
main.writeToPlc(0xc04200e100, 0xd, 0x1c7, 0x0, 0x3, 0x2, 0xc0420420c0, 0xc042040070)
        C:/Users/user/go/src/client/main.go:146 +0x374
created by main.main
        C:/Users/user/go/src/client/main.go:51 +0x5da
```

**Comment by JekRock** [comment]
I think I've found the solution. I've changed idle timeout and everything works fine.
